### ISSUE TITLE
Folder for "git clone"

### ISSUE THREAD

**Issue by YurBurGer** [AufarZakiev/Gazebo_heightmap_preparation_node#10]
Probably required to change folder from "catkin_ws" to "catkin_ws/src"

**Comment by YurBurGer** [comment]
Changed

**Comment by AufarZakiev** [comment]
https://github.com/AufarZakiev/Gazebo_heightmap_preparation_node/commit/fd12deb9063d0e9c96b35498f8d72da33528063f

Fixing commit.
