### ISSUE TITLE
Manuals

### ISSUE THREAD

**Issue by YurBurGer** [AufarZakiev/Gazebo_heightmap_preparation_node#13]
Expand manuals with node usage examples.

**Comment by AufarZakiev** [comment]
https://github.com/AufarZakiev/Gazebo_heightmap_preparation_node/commit/a62e360d2fe30bfe309b83a214c779b72517552a 
Made launch file integrated with boost::options.
Going to add some examples in README.md

**Comment by AufarZakiev** [comment]
https://github.com/AufarZakiev/Gazebo_heightmap_preparation_node/commit/f388c20f8ad8b37c7675cf593da9dbb564491928 
Commit with multiple examples.

**Comment by YurBurGer** [comment]
@AufarZakiev add examples with rosrun and app names

**Comment by AufarZakiev** [comment]
README updated, closing issue.
