### ISSUE TITLE
Laggs!

### ISSUE THREAD

**Issue by YurBurGer** [AufarZakiev/Gazebo_heightmap_preparation_node#15]
This world LAGS!
[worlds.zip](https://github.com/AufarZakiev/Gazebo_heightmap_preparation_node/files/1471790/worlds.zip)

**Comment by AufarZakiev** [comment]
Checked this world on my machine. 
RTF = 1.0
FPS is excellent.
Gazebo 2.2 used.
System parameters: 23,5 GiB RAM, Intel® Core™ i7-4700HQ CPU @ 2.40GHz × 8, GeForce GTX 770M.
Try to change "Use terrrain paging" property in world-file to "true".

**Comment by YurBurGer** [comment]
@AufarZakiev Requires testing on multiple different machines

**Comment by YurBurGer** [comment]
Solved by migrating from Unity to Gnome. FPS still low, but system doesn't hang out.
